spring.application.name=BTS
server.port=8090
# Database related config
spring.datasource.url=jdbc:postgresql://localhost:5432/bts
spring.datasource.username=postgres
spring.datasource.password=debanjan
# Optional: Connection pool settings
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.show-sql=true
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=ERROR