spring.application.name=BTS
server.port=8090
# Database related config
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bts}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:debanjan}
spring.jpa.hibernate.ddl-auto=update
# Optional: Connection pool settings
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.show-sql=true
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=ERROR